### ISSUE TITLE
Are new dependencies allowed? (Numba and/or numexpr in particular)

### ISSUE THREAD

**Issue by magicgoose** [simon-r/dr14_t.meter#44]
There's possibility to make this code run faster by using Numba or Numexpr and I think I might give it a try.
But of course there are downsides (installation gets a bit harder and fat, maybe also code will be a bit more difficult to read) so I'd like to ask before trying.

(so far I tried Numba for some trivial things, like compute sum of squares of all bytes of a big file, and it can deliver about 2x of speed compared to what's possible with just Numpy. I think I can achieve some speedup here, too)

A "speedup" dependency may be also optional (non-optimized code is used if the dependency is not installed) but I personally don't think that having to support 2 implementations is a great idea.

**Comment by simon-r** [comment]
A well programmed numpy, IMHO, is sufficiently fast.
For me the real optimization is adding the code in OpenCL.

numexpr seems interesting.

**Comment by magicgoose** [comment]
Numpy's biggest limitation are intermediate array allocations. Any of these (numexpr, numpy) can be used to evade them. Numba seems faster in practice, the only drawback is that it requires LLVM at run time + a bit harder to install at least on some systems. Numexpr on the other hand is trivial to install, like any other package from pip.

OpenCL might be even better but it's also harder ;D
Getting something like 2x speedup almost for free is good too I think.

**Comment by simon-r** [comment]
From this point of view we must write an optimized code in C, and we don't have the problem of some rare external library.

OpenCL is de-facto supported by all PC and distro.

Another point: my code spent a lot of time for reading and decoding the tracks, so the advantage of any optimization is quite low.

**Comment by sp-1234** [comment]
> Another point: my code spent a lot of time for reading and decoding the tracks, so the advantage of any optimization is quite low.

Yes I thought about it too.
I plan to make it process data while reading (not read all at once), this will also allow supporting huge files.

**Comment by sp-1234** [comment]
Wrote a PoC which reads audio data directly from ffmpeg pipe, in blocks of the same size which is used for DR calculation, and for each block computes max of absolute values (peaks), and sum of squares (most heavy part for RMS) per channel.  
Using only numpy, no other dependencies. However, array copies are reduced when possible by using in-place numpy operations.

This is consistently 3.6x faster than dr14_t.meter's routine on my machine (for stereo files; I tried to also compare 6-channel files but dr14_t.meter seems to not be able to read them). And of course, it uses a lot less memory, because entire audio data is not put in RAM at the same time.

Maybe numexpr may make it even faster, didn't try it yet.

I did it separately because this would require rather big refactoring in dr14 codebase to make it read from pipe without temp files, and I first wanted only to compare speeds.

I will upload the code later to a repository from my normal account. stay tuned

**Comment by magicgoose** [comment]
Yeah, here it is: https://gist.github.com/magicgoose/618b04764505e8f7067ebcefe850771a
(I didn't bother to support Python 2 yet, but it's doable)

**Comment by simon-r** [comment]
Very interesting solution.

**Comment by sp-1234** [comment]
Also
https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.partition.html
may be used instead of full sorting of peak values, because we need only 2nd-to-max value and order of all other values is unimportant. But this is very tiny optimization compared to the above.

**Comment by sp-1234** [comment]
wrote complete DR computation with that method, results are correct, speed is virtually the same as simply computing sums of squares (as expected). will put it into a repository later

**Comment by magicgoose** [comment]
@simon-r https://github.com/magicgoose/simple_dr_meter (feel free to take anything from there of course)
